package mcodec

object FailureParityFixtures:
  case class Point(x: Int, y: Int) derives MCodec
  enum Shape derives MCodec:
    case Circle(radius: Int)
    case Square(side: Int)
  // NEW 4-level deep-nested fixture (deeper than the existing 3-level Root/User/Address):
  case class D(v: Int) derives MCodec
  case class C(d: D) derives MCodec
  case class B(c: C) derives MCodec
  case class A(b: B) derives MCodec // bad leaf -> path b.c.d.v

// Bad-form CBOR hex below was GENERATED by splicing observed `toCborHex` output, never hand-authored:
//   Point(1,2)      = A2 6178 01 6179 02         (map2: "x"->1, "y"->2)
//   Shape.Circle(1) = A1 66436972636C65 A1 6672616469757301
//   A(B(C(D(7))))   = A1 6162 A1 6163 A1 6164 A1 6176 07
class FailureParityTest extends munit.FunSuite, JsonConv, CborConv:
  import FailureParityFixtures.*

  // 1. Missing field — typed subclass MissingField (JSON proven, CBOR discovered).
  test("missing field — JSON — MissingField + envelope"):
    val rf = intercept[ReadFailure](fromJson[Point]("{}"))
    assert(rf.isInstanceOf[MissingField], s"got ${rf.getClass}")
    assert(rf.getMessage.contains("Failed to read Point"))
    assert(rf.getMessage.contains("missing"))

  test("missing field — CBOR — MissingField + envelope"):
    // A0 = empty CBOR map = product with no fields
    val rf = intercept[ReadFailure](fromCborHex[Point]("A0"))
    assert(rf.isInstanceOf[MissingField], s"CBOR missing-field divergence — got ${rf.getClass}")
    assert(rf.getMessage.contains("Failed to read Point"))
    assert(rf.getMessage.contains("missing"))

  // 2. Unknown case — typed subclass UnknownCase (JSON proven, CBOR discovered).
  test("unknown case — JSON — UnknownCase + discriminator"):
    val rf = intercept[ReadFailure](fromJson[Shape]("""{"Triangle":{}}"""))
    assert(rf.isInstanceOf[UnknownCase], s"got ${rf.getClass}")
    assert(rf.getMessage.contains("Failed to read Shape"))
    assert(rf.getMessage.contains("unknown case"))
    assert(rf.getMessage.contains("Triangle"))

  test("unknown case — CBOR — UnknownCase + discriminator"):
    // A1 68 "Triangle" A0  = map1 { text "Triangle" -> empty map } (observed)
    val rf = intercept[ReadFailure](fromCborHex[Shape]("A168547269616E676C65A0"))
    assert(rf.isInstanceOf[UnknownCase], s"CBOR unknown-case divergence — got ${rf.getClass}")
    assert(rf.getMessage.contains("unknown case"))
    assert(rf.getMessage.contains("Triangle"))

  // 3. Type mismatch — plain ReadFailure, backend-specific leaf wording.
  test("type mismatch — JSON — number leaf reason"):
    val rf = intercept[ReadFailure](fromJson[Point]("""{"x":"abc","y":2}"""))
    assert(rf.getMessage.contains("number"), s"got ${rf.getMessage}")

  test("type mismatch — CBOR — major-type leaf reason"):
    // A2 6178 6161 6179 02 = {"x":"a","y":2} but x is text (major 3) where Int expected (observed)
    val rf = intercept[ReadFailure](fromCborHex[Point]("A261786161617902"))
    assert(rf.getMessage.contains("expected integer, got major type"), s"got ${rf.getMessage}")

  // 4. Deep-nested — plain ReadFailure leaf, identical dotted path b.c.d.v on BOTH backends.
  test("deep-nested — JSON — full dotted path b.c.d.v"):
    val rf = intercept[ReadFailure](fromJson[A]("""{"b":{"c":{"d":{"v":"x"}}}}"""))
    assert(rf.getMessage.contains("b.c.d.v"), s"got ${rf.getMessage}")
    assert(rf.getCause != null)

  test("deep-nested — CBOR — same dotted path b.c.d.v"):
    // A1 6162 A1 6163 A1 6164 A1 6176 6178 = A(B(C(D(v)))) with leaf v as text "x" (observed)
    val rf = intercept[ReadFailure](fromCborHex[A]("A16162A16163A16164A161766178"))
    assert(rf.getMessage.contains("b.c.d.v"), s"got ${rf.getMessage}")
