name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@v1.14.0
        with:
          scala-cli-version: 1.14.0
      - run: scala-cli --power compile .
      - run: scala-cli --power test .
